export enum HomePageActionTypes {
  GET_HOME_PAGE_DATA_REQUEST = "GET_HOME_PAGE_DATA_REQUEST",
  GET_HOME_PAGE_DATA_SUCCESS = "GET_HOME_PAGE_DATA_SUCCESS",
  GET_HOME_PAGE_DATA_FAIL = "GET_HOME_PAGE_DATA_FAIL",
}
